In [1]:
# class
class Student:
    def __init__(self):
        self.hello = "안녕하세요."
        
    def greeting(self):   # 매서드
        print(self.hello)

In [2]:
# stu_a와 stu_b는 독립적으로 존재
stu_a = Student() # 클래스로부터 인스턴스 초기화
stu_b = Student()

In [3]:
stu_a.greeting()

안녕하세요.


In [4]:
stu_b.greeting()

안녕하세요.


In [5]:
stu_a.name = "학생A"

In [6]:
print(stu_a.hello)

안녕하세요.


In [7]:
print(stu_a.name)

학생A


In [8]:
print(stu_b.hello)

안녕하세요.


In [9]:
print(stu_b.name)

AttributeError: 'Student' object has no attribute 'name'

In [28]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

In [29]:
p1 = Person("name1", 40)
p2 = Person("name2", 32)

In [30]:
p1.__dict__

{'name': 'name1', 'age': 40}

In [31]:
p2.__dict__

{'name': 'name2', 'age': 32}

In [33]:
class Person2:
    def __init__(self, name, age, address):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")

In [34]:
maria = Person2("마리아", 23, "서울시 마포구")
maria.greeting()

안녕하세요. 제 이름은 마리아입니다.


In [63]:
class Person3:
    def __init__(self, name, age, address):
        self.name = name
        self.age = age
        self.address = address

In [62]:
list_m = []
list_m.append(input("이름은 무엇인가요?"))
list_m.append(int(input("나이는 무엇인가요?")))
list_m.append(input("주소는 무엇인가요?"))

list_j = []
list_j.append(input("이름은 무엇인가요?"))
list_j.append(int(input("나이는 무엇인가요?")))
list_j.append(input("주소는 무엇인가요?"))


maria1 = Person3(list_m[0], list_m[1], list_m[2])

print(f"첫번째 이름:{maria1.name}")
print(f"첫번째 이름:{maria1.age}")
print(f"첫번째 이름:{maria1.address}")

james = Person3(list_j[0], list_j[1], list_j[2])

print(f"두번째 이름:{james.name}")
print(f"두번째 이름:{james.age}")
print(f"두번째 이름:{james.address}")

이름은 무엇인가요? 마리아
나이는 무엇인가요? 20
주소는 무엇인가요? 서울시 강남구
이름은 무엇인가요? 제임스
나이는 무엇인가요? 21
주소는 무엇인가요? 서울시 구로구


첫번째 이름:마리아
첫번째 이름:20
첫번째 이름:서울시 강남구
두번째 이름:제임스
두번째 이름:21
두번째 이름:서울시 구로구


In [91]:
class Person4:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요"
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet # __를 붙이면 비공개로 설정 가능
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
    def amount(self):
        print(self.__wallet)
    
    def pay(self, amount):
        if self.__wallet < amount:
            print("돈이 모자랍니다.")
            return
        self.__wallet -= amount

In [92]:
lbh = Person4("이병호", 25, "경기도 안양", 100000)

In [69]:
print(lbh.name)

이병호


In [70]:
print(lbh.age)

25


In [71]:
print(lbh.address)

경기도 안양


In [80]:
print(lbh.wallet) # 클래스 바깥에서 비공개 속성에 접근하면 에러가 발생

AttributeError: 'Person4' object has no attribute 'wallet'

In [93]:
lbh.amount() # 10만원을 가지고 있다.

100000


In [94]:
lbh.pay(50000) # 5만원 사용

In [95]:
lbh.amount() # 남은 돈

50000


In [96]:
lbh.pay(60000) # 6만원 사용

돈이 모자랍니다.


In [128]:
class Champion:
    def __init__(self, hp, mp, ap):
        self.hp = hp
        self.mp = mp
        self.ap = ap
        
    def tibber(self):
        print(f"티버: 피해량 {self.ap * 0.65 + 400}")

In [130]:
t = list(map(float, input("체력, 마나, AP를 입력하세요.").split(" ")))

Annie = Champion(t[0],t[1],t[2])

체력, 마나, AP를 입력하세요. 511.68 334.0 298


In [131]:
Annie.tibber()

티버: 피해량 593.7


In [132]:
hp, mp, ap = map(float, input("체력, 마나, AP를 입력하세요.").split(" "))

Annie = Champion(hp, mp, ap)

체력, 마나, AP를 입력하세요. 1803.68 1184.0 645


In [133]:
Annie.tibber()

티버: 피해량 819.25


## Numpy

In [2]:
import numpy as np # 한번만 써놓으면 밑에 코드에 적용

In [159]:
ar = np.array([_ for _ in range(10)])

In [157]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
ar.shape

(10,)

In [165]:
type(ar)

numpy.ndarray

In [163]:
ar2 = np.array([0.1, 5, 4, 12, 0.5])

In [164]:
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [169]:
ar.dtype

dtype('int32')

In [168]:
ar2.dtype

dtype('float64')

In [190]:
ar3 = np.array([_ for _ in range(3, 10, 3)], 'i8') # int8bytes --> 8*8bit
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [192]:
ar4 = np.array([_ for _ in range(2, 10, 2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [186]:
# 'U8' 유니코드 8글자 자료형을 명시적으로 선언
# 그래서 시퀀스 자료형 중 제일 큰 값이 <U8이지만 <U8로 타입이 지정되었다.
ar5 = np.array(["가나다라마","바사아","자","차카"], 'U8')
print(ar5)
print(ar5.dtype)
# <U8은 최대 8글자의 유니코드 자료형이다.

['가나다라마' '바사아' '자' '차카']
<U8


In [193]:
x = np.array([1, 2, 3],dtype='f')
x.dtype

dtype('float32')

In [198]:
x[0] + x[1] #실수형으로 더하기

'12'

In [195]:
x = np.array([1, 2, 3],dtype='U')
x.dtype

dtype('<U1')

In [197]:
x[0] + x[1] #문자열로 더하기 1+2

'12'

In [199]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

answer = [2 * d for d in data]

answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [200]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [203]:
list_samp = [_ for _ in range(3)]
print(list_samp * 3)

[0, 1, 2, 0, 1, 2, 0, 1, 2]


In [207]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [208]:
2 * a + b

array([12, 24, 36])

In [209]:
a == 2

array([False,  True, False])

In [210]:
b > 10

array([False,  True,  True])

In [220]:
(a == 2) & (b > 10)

array([False,  True, False])

In [227]:
c = np.array([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [228]:
c.shape

(2, 3)

In [235]:
n = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
n

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [244]:
d = np.array([[[1,2,3,4,],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [245]:
d.shape

(2, 3, 4)

In [250]:
print(a.ndim) # 1차원
print(c.ndim) # 2차원
print(d.ndim) # 3차원

1
2
3


In [251]:
a = np.array([0,1,2,3,4])

In [252]:
a[2]

2

In [255]:
a[-1]

4

In [256]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [257]:
a[0, 0]

0

In [259]:
a[0, 1]

1

In [263]:
a[-1, -1]

5

In [264]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [268]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [270]:
a[:, 1] # 첫번째 열 전체

array([1, 5])

In [271]:
a[1, 1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [277]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [279]:
np.array([_ for _ in range(8)]).reshape(2,4) # 갯 수에 맞춰 reshap을 사용하면 나누어 준다.

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
7 // 14 // 6,7 // 7,12 // 3,4  8,9

In [296]:
m = np.array([_ for _ in range(15)]).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [295]:
m[1, 2]

7

In [297]:
m[-1, -1]

14

In [299]:
m[1, 1:3]

array([6, 7])

In [302]:
m[1: ,2]

array([ 7, 12])

In [308]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [310]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [314]:
c = np.zeros((5,2),dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [12]:
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [317]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE" # U4라서 E는 짤림
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [318]:
e = np.ones((2,3,4),dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [319]:
f = np.ones_like(b, dtype="f")
f

array([1., 1., 1.], dtype=float32)

In [322]:
q = np.empty((4,3)) # 임시로 4,3짜리의 배열을 생성
q

array([[1.01091490e-311, 2.76676762e-322, 0.00000000e+000],
       [0.00000000e+000, 1.14587773e-312, 1.16095484e-028],
       [3.74168445e+233, 1.94950106e-057, 4.31722897e-096],
       [9.80058441e+252, 1.23971686e+224, 1.03439406e+295]])

In [324]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [325]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [342]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [343]:
np.logspace(0, 100, 5)

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [344]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [346]:
A.T # .T는 행과 열을 바꿔주는 메서드가 아닌 속성

array([[1, 4],
       [2, 5],
       [3, 6]])

In [347]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [356]:
b = a.reshape(3,-1)  # == (3,4) -1은 auto느낌 알아서 맞춰줌
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [361]:
b.flatten() # 다차원의 배열을 1차원으로 바꿔준다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [362]:
b.ravel() # 다차원의 배열을 1차원으로 바꿔준다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [364]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [369]:
np.vstack([b1,b2]) # b1과 b2를 합쳐준다.

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [370]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [371]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [374]:
np.dstack([c1,c2]) 

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [386]:
c = np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [387]:
c.shape

(2, 3, 4)

In [392]:
c = np.stack([c1,c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [393]:
c.shape

(3, 2, 4)

In [394]:
c = np.stack([c1,c2], axis=2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [395]:
c.shape

(3, 4, 2)

In [399]:
np.r_[np.array([1,2,3]), np.array([4,5,6])] # r_ 좌우를 연결해주는 메서드 / (소괄호)가 아닌 [대괄호]를 쓴다.

array([1, 2, 3, 4, 5, 6])

In [400]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [404]:
a = np.array([[0,1,2], [3,4,5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [405]:
np.tile(a, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [4]:
f = np.zeros((3,3))
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
g = np.ones((3,2))
g

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
h = np.array([_ for _ in range(10,151,10)]).reshape(3,5)
h

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [10]:
q = np.hstack([f, g])
q

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [15]:
i = np.c_[np.zeros((3,3)), np.ones((3,2))] 
i 

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [17]:
i == q # q == i

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
np.vstack(([i, h])*2)

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])