In [286]:
import numpy as np

In [36]:
class Calculator:
    def __init__(self):
        self.value = 0
    
    def add(self, n=None, *args):
        if n == None:
            print("숫자를 입력해주세요.")
        elif type(n) == range:
            self.value += sum(n)
            print(f"현재 값은 {self.value}입니다.")
        else:
            self.value += int(sum([_ for _ in (n,*args)]))
            print(f"현재 값은 {self.value}입니다.")
              
    def minus(self, n=None, *args):
        if n == None:
            print("숫자를 입력해주세요.")
        elif type(n) == range:
            self.value += sum(n)
            print(f"현재 값은 {self.value}입니다.")
        else:
            self.value -= int(sum([_ for _ in (n,*args)]))
            print(f"현재 값은 {self.value}입니다.")

        
    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")

In [37]:
c = Calculator()

In [38]:
c.add(100)

현재 값은 100입니다.


In [39]:
c.minus(20)

현재 값은 80입니다.


In [40]:
c.add()

숫자를 입력해주세요.


In [41]:
c.minus(10,20)

현재 값은 50입니다.


In [42]:
c.add(range(1,6))

현재 값은 65입니다.


In [68]:
#T
import numpy as np

class TCalculator:
    def __init__(self):
        self.value = 0
    
    def add (self, *number):
        if len(number) > 0:
            num = np.array(number)
            print(num)
            self.value += np.sum(num)
        else:
            print("숫자를 입력해주세요.")
    
    def minus (self, *number):
        if len(number) > 0:
            num = np.array(number)
            self.value -= np.sum(num)
        else:
            print("숫자를 입력해주세요.")
            
    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")

In [69]:
c2 = TCalculator()

In [70]:
c2.add(100)
c2.show_value()

[100]
현재 값은 100입니다.


In [71]:
c2.minus(20)
c2.show_value()

현재 값은 80입니다.


In [72]:
c2.add()

숫자를 입력해주세요.


In [73]:
c2.minus(10,20)
c2.show_value()

현재 값은 50입니다.


In [74]:
c2.add(range(1,6))
c2.show_value()

[[1 2 3 4 5]]
현재 값은 65입니다.


## 백터화 연산

In [99]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [94]:
a == b

array([False,  True, False,  True])

In [95]:
a >= b

array([False,  True,  True,  True])

In [97]:
np.all(a == b)

False

In [101]:
np.all(a == c) # 각 요소를 일일히 비교하는 것이 아니라 배열의 모든 원소가 다 같은지

True

In [103]:
# 스칼라
a = np.array([1,2,3,4])

a * 10

array([10, 20, 30, 40])

## 브로드캐스팅

- 넘파이 배열은 모양이 다른 배열간의 연산이 가능하도록 배열의 크기를 변환시켜주는 브로드캐스팅을 지원

불가능한 경우 1이나 같은 숫자가 아닐 때

In [106]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

a * b

array([ 4,  4,  6, 16])

In [109]:
# 스칼라 곱
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [110]:
# 배열간의 곱
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [112]:
x = np.array(range(5))
x

array([0, 1, 2, 3, 4])

In [114]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [116]:
x + y

array([1, 2, 3, 4, 5])

In [118]:
x + 1

array([1, 2, 3, 4, 5])

- 최대/최소: min, max, argmin, argmax
- 통계: sum, mean, median, std, var
- 불리언: all, any

In [122]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [123]:
x.sum()

10

In [124]:
np.sum(x)

10

In [126]:
x = np.arange(12).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
x.sum(axis=0) #행 간의 연산 결과

array([12, 15, 18, 21])

In [143]:
x.sum(axis=1) # 열 간의 연산 결과

array([[20, 25],
       [70, 75]])

In [140]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [134]:
x.min()

0

In [135]:
np.min(x)

0

In [141]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [167]:
x.min(axis=1)

array([[ 0,  1],
       [10, 11]])

In [168]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [154]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [155]:
x.argmin()

0

In [156]:
np.argmin(x)

0

In [157]:
x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [165]:
x.argmin(axis=1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [159]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [160]:
x.max()

19

In [161]:
np.max(x)

19

In [162]:
x.max(axis=0)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [163]:
x.max(axis=1)

array([[ 8,  9],
       [18, 19]])

In [164]:
x.max(axis=2)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [170]:
x.argmax()

19

In [171]:
np.argmax(x)

19

In [176]:
x.argmax(axis=0) # 인덱스 값을 가져오는것!

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [177]:
x.argmax(axis=1) # 인덱스 값을 가져오는것!

array([[4, 4],
       [4, 4]], dtype=int64)

In [178]:
x.argmax(axis=2) # 인덱스 값을 가져오는것!

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [190]:
x = np.array([1,2,3,1])

In [191]:
x.mean() # 평균을 구합니다.

1.75

In [192]:
np.median(x) # 중간값을 구합니다.

1.5

- np.all()은 하나라도 True이면 True 하나라도 False이면 False

- np.any()는 True가 하나라도 있으면 True, False가 하나라도 있으면 False

In [196]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [198]:
# 전체의 최댓값
practice.max()

9.0

In [220]:
# 각 행의 합
practice.sum(axis=0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [219]:
# 각 행의 최댓값
practice.max(axis=0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [218]:
# 각 열의 평균
practice.mean(axis=1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [221]:
# 각 열의 최솟값
practice.min(axis=1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

In [224]:
a = np.array([[4,3,5,6],[1,12,11,9],[2,15,1,14]])
a

array([[ 4,  3,  5,  6],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [230]:
# 정렬
np.sort(a)

array([[ 3,  4,  5,  6],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [228]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  6],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [272]:
a = np.array([42,38,12,25])
j = np.argsort(a) # 작은순서대로 인덱스번호를 알려준다.
j

array([2, 3, 1, 0], dtype=int64)

In [280]:
a[j]

array([12, 25, 38, 42])

In [274]:
np.sort(a)

array([12, 25, 38, 42])

In [245]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [343]:
scores = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
scores

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [380]:
c = np.argsort(scores)
c[1]

array([0, 3, 1, 2], dtype=int64)

In [390]:
scores[:,c[1]]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [558]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [560]:
len(x) # len함수로 데이터의 개수를 구할 수 있다.

5

In [561]:
# 표본 평균
np.mean(x) #평균

3.0

In [563]:
# 표본 분산
np.var(x) #분산

2.0

In [565]:
np.var(x, ddof=1) #비편향 분산. 추후 공부하게 됨

2.5

In [569]:
np.std(x) #표준 편차

1.4142135623730951

In [571]:
np.median(x) #중앙값 크기대로 정렬하였을 때 가장 가운데 있는 수 
                # 짝수이면 가장 가운데 있는 두 수의 평균

3.0

사분위수는 예를 들어 100을 4등분하면 시작(0)과 끝점(100)을 제외하고  
 0    25    50    75    100 이렇게 나누어 지는데  
25가 사분위수  (1/4지점)  
50이 2사분위수 (2/4지점)  
75가 3사분위수 (3/4지점)  

In [572]:
np.random.seed(0) # 시드 설정하기

In [404]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [405]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [406]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [407]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [409]:
np.random.shuffle(x) # 데이터의 순서를 바꾸려면
x

array([5, 7, 6, 1, 9, 3, 0, 2, 8, 4])

## 데이터 샘플링  
이미 있는 데이터 집합에서 일부로 무작위로 선택하는 것을 샘플링 or 표본선택이라고 한다.  
numpy.random.choice(a, size=None, replace=True, p=None)  

- a : 배열이면 원래의 데이터,정수이면 arange(a) 명령으로 데이터 생성
- size : 정수.샘플 숫자.
- replace : 불리언.True이면 한번 선택한 데이터를 다시 선택가능
- p : 배열.각 데이터가 선택될 수 있는 확률

In [413]:
np.random.choice(5, 5, replace=False) # shuffle 명령과 같다.

array([0, 3, 2, 4, 1])

In [418]:
np.random.choice(5, 3, replace=False) # 3개만 선택

array([3, 1, 0])

In [421]:
np.random.choice(5, 10) # 반복해서 10개 선택

array([1, 1, 3, 0, 0, 1, 2, 4, 2, 0])

In [425]:
np.random.choice(5, 10, p=(0.1, 0, 0.3, 0.6, 0)) # 선택 확률을 다르게 해서 10개 선택

array([2, 3, 2, 3, 2, 2, 3, 0, 3, 0])

## 난수 생성  
- rand: 0부터 1사이의 균일 분포
- randn: 표준 정규 분포
- randint: 균일 분포의 정수 난수

In [428]:
np.random.rand(10) 

array([0.13547406, 0.29828233, 0.56996491, 0.59087276, 0.57432525,
       0.65320082, 0.65210327, 0.43141844, 0.8965466 , 0.36756187])

In [429]:
np.random.rand(3,5)

array([[0.43586493, 0.89192336, 0.80619399, 0.70388858, 0.10022689],
       [0.91948261, 0.7142413 , 0.99884701, 0.1494483 , 0.86812606],
       [0.16249293, 0.61555956, 0.12381998, 0.84800823, 0.80731896]])

In [426]:
np.random.randn(10)

array([-1.16514984,  0.90082649,  0.46566244, -1.53624369,  1.48825219,
        1.89588918,  1.17877957, -0.17992484, -1.07075262,  1.05445173])

In [427]:
np.random.randn(3,5)

array([[-0.40317695,  1.22244507,  0.20827498,  0.97663904,  0.3563664 ],
       [ 0.70657317,  0.01050002,  1.78587049,  0.12691209,  0.40198936],
       [ 1.8831507 , -1.34775906, -1.270485  ,  0.96939671, -1.17312341]])

In [498]:
np.random.seed(0)

In [499]:
a = np.random.choice(2, 100)
a

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [501]:
a.sum()/100

0.56

In [550]:
np.random.seed(0)

In [551]:
d = np.random.randint(1, 7, 100) # randint
d 

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2, 6, 1,
       2, 5, 4, 1, 4, 6, 1, 3, 4, 1, 2, 4, 6, 4, 4, 1, 2, 2, 2, 1, 3, 5,
       4, 4, 3, 5, 3, 1, 1, 5, 6, 6, 1, 5, 2, 5, 2, 3, 3, 1, 2, 2, 2, 2,
       4, 4, 3, 4, 1, 4, 6, 5, 2, 3, 5, 4, 5, 5, 5, 4, 5, 5, 5, 1, 5, 4,
       3, 6, 6, 6, 1, 2, 6, 2, 4, 1, 6, 1])

In [553]:
d.sum()/100

3.42

In [556]:
np.bincount([1,1,2,2,2,3], minlength=6) # 0의 갯수 1의 갯수 2의 갯수 ... 5의 갯수 minlength=6

array([0, 2, 3, 1, 0, 0], dtype=int64)